### ISSUE TITLE
Missing checkbox for battery

### ISSUE THREAD

**Issue by ruizmarc** [longzheng/homebridge-fronius-inverter-lights#19]
Hi,

First of all, thanks for sharing this plugin, I really liked your idea and I'm already using it with my inverter :) 

I've noticed that although is a configuration option in JSON, it does not appear a checkbox to enable or disable battery accessory. It would be great to have that checkbox in the UI.

Thanks for your work!

**Comment by longzheng** [comment]
Thanks for the reminder. I published a new version with the configuration for battery.
