### ISSUE TITLE
可以咨询一些homeassistant的问题吗？

### ISSUE THREAD

**Issue by blue-eric** [longzheng/homebridge-fronius-inverter-lights#20]
你好，我在teslamate上看见你做了很多homeassistant、MQTT改善的推送，我在实际使用中遇到一下问题，但是因为我是菜鸟，所以想跟你这咨询一些解决方法，可以吗？

**Comment by longzheng** [comment]
Hi. Sorry my Chinese is not good enough to help you in Chinese. It would be best for you to post your question on Teslamate so other people can see it too.
