### ISSUE TITLE
how to check pv-status directly via solarweb?

### ISSUE THREAD

**Issue by Scoo27** [longzheng/homebridge-fronius-inverter-lights#23]
hi there,
i have a fronius primo gen24 and a symo inverter, both have half of the solarcells for power-generation.
until now, the gen24 local-ip webinterface showed the consumtion and creation of both inverters.
After an update the gen24 only shows the creation of his own creation and i have to look into solwarweb to check the whole system (powercreation and consumption etc.).
Is ist possible to take those values from solarweb to dispay them in homebridge-Plugin?
If yes: what do i have to do?

thanks in advance

**Comment by longzheng** [comment]
I think what you're describing is called daisy chaining where multiple Fronius inverters can be connected and a single "master" datamanager aggregates the metrics from all inverters.

I wasn't aware that it supported chaining inverters of different models (e.g. Gen24 and Symo), but if you say it worked then it must have worked.

I'm not sure why an update removed/broke that functionality.

Unfortunately this plugin is designed to interface directly with the local datamanager. Going via Solarweb has a lot more complexity that I didn't want to do. 

I would recommend maybe doing some Googling or reaching out to Fronius support to figure out why the update broke your daisy chain functionality and hopefully it can be restored in a future update.
