### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by na-ma-ste** [longzheng/homebridge-fronius-inverter-lights#26]
Hi,

I wanted to enquire whether it is possible to activate or deactivate the individual smart meter elements (PV, Gird, Load, Battery) for display in HomeKit. So that, for example, the battery can simply be deactivated and is not displayed as a lamp.

Best

**Comment by longzheng** [comment]
Only the battery is optional, you can hide in the config `"battery": false`.

**Comment by longzheng** [comment]
Can I ask why you want to hide/deactivate some of the lamps? In theory you could just move them to a HomeKit room you don't use and remove from the home screen.
