### ISSUE TITLE
Plugin crashes Homebridge if the inverter is not connected to internet.

### ISSUE THREAD

**Issue by oandpg** [longzheng/homebridge-fronius-inverter-lights#27]
Hi the plugin will crash homebridge and put it into a restart loop when the plugin cannot contact the inverter. Occasionally my fronius gen24 loses the internet connection and it needs restarting, but in the meantime homebridge crashes repeatedly. This is usually how I find out the inverter is offline, because all the Homebridge items stop working. Easy to reproduce, just add a fake ip

![IMG_0607](https://github.com/user-attachments/assets/f874796d-f7df-4d58-bfe9-8a2a943308cb)

**Comment by longzheng** [comment]
Ah interesting. I can look into that but in the interim I would recommend creating a child bridge for this plugin to prevent it crashing.

**Comment by oandpg** [comment]
Works as a child plugin and doesn’t cause Homebridge to crash. I can live with this if it is unfixable. Thanks for the quick response.
