### ISSUE TITLE
Question Lightbulb brightness 

### ISSUE THREAD

**Issue by Adatis22** [longzheng/homebridge-fronius-inverter-lights#6]
Hi 
Thanks for this plugin. I was wondering about the Lightbulb brightness lux which represents watts.
What value is this actually showing? The load or export or even a combination?

Thanks for your time and help
Best regards
Nicolas

**Comment by longzheng** [comment]
The readme describes which bulb shows what
```
Export - net export (lightbulb brightness % relative to solar generation)
Import - net import (lightbulb brightness % relative to solar generation)
Load - the amount of grid load
PV - the amount of solar generation (lightbulb brightness % relative to max PV capacity)
```
